apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: zyew
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zyew
    app.kubernetes.io/part-of: byoc-app-rdsd
  name: zyew
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: zyew
status:
  loadBalancer: {}
